// Placeholder data so every screen is fully functional before the Postgres
// backend exists. Swap the functions in services/api.js for real calls and
// nothing in the pages/components needs to change.
import { loadPersisted } from "./persist";

export const categories = [
  "Oil Items",
  "Pulses",
  "Masala Items",
  "Flour Items",
  "Noodles & Semiya",
  "Skin Care",
];

const emojiByCategory = {
  "Oil Items": "🫙",
  Pulses: "🌾",
  "Masala Items": "🌶️",
  "Flour Items": "🍪",
  "Noodles & Semiya": "🧃",
  "Skin Care": "🥛",
};

const seedProducts = [
  [
    {
      id: "P001",
      name: "Mutton Masala / Kuruma Masala 250g",
      category: "Masala Items",
      price: 135,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001001",
    },
    {
      id: "P002",
      name: "Paruppu Podi 100g",
      category: "Masala Items",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001002",
    },
    {
      id: "P003",
      name: "Chilli Powder 100g",
      category: "Masala Items",
      price: 50,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001003",
    },
    {
      id: "P004",
      name: "Malli Powder (Coriander) 100g",
      category: "Masala Items",
      price: 40,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001004",
    },
    {
      id: "P005",
      name: "Idli Podi 250g",
      category: "Masala Items",
      price: 140,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001005",
    },
    {
      id: "P006",
      name: "Idli Podi 100g",
      category: "Masala Items",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001006",
    },
    {
      id: "P007",
      name: "Sambar Podi 250g",
      category: "Masala Items",
      price: 135,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001007",
    },
    {
      id: "P008",
      name: "Karuveppilai Podi 100g",
      category: "Masala Items",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001008",
    },
    {
      id: "P009",
      name: "Chicken Masala 100g",
      category: "Masala Items",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001009",
    },
    {
      id: "P010",
      name: "Instant Rasam Podi 100g",
      category: "Masala Items",
      price: 80,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001010",
    },

    {
      id: "P011",
      name: "Pepper (Milagu) 50g",
      category: "Pulses",
      price: 47,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001011",
    },
    {
      id: "P012",
      name: "Cardamom (Elakkai) 50g",
      category: "Pulses",
      price: 200,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001012",
    },
    {
      id: "P013",
      name: "Fenugreek (Vendhayam) 250g",
      category: "Pulses",
      price: 30,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001013",
    },
    {
      id: "P014",
      name: "Urad Dal (Ulundhu) 500g",
      category: "Pulses",
      price: 75,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001014",
    },
    {
      id: "P015",
      name: "Cumin Seed (Seeragam) 100g",
      category: "Pulses",
      price: 45,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001015",
    },
    {
      id: "P016",
      name: "Double Beans 250g",
      category: "Pulses",
      price: 40,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001016",
    },
    {
      id: "P017",
      name: "Ragi 1kg",
      category: "Pulses",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001017",
    },
    {
      id: "P018",
      name: "Ragi 500g",
      category: "Pulses",
      price: 40,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001018",
    },
    {
      id: "P019",
      name: "Black Gram (Ulundhu) 500g",
      category: "Pulses",
      price: 65,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001019",
    },
    {
      id: "P020",
      name: "Samai (Little Millet) 500g",
      category: "Pulses",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001020",
    },
    {
      id: "P021",
      name: "Ellu (Sesame) 500g",
      category: "Pulses",
      price: 120,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001021",
    },
    {
      id: "P022",
      name: "Pearl Millet (Naattu Kambu) 500g",
      category: "Pulses",
      price: 50,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001022",
    },
    {
      id: "P023",
      name: "Barnyard Millet (Kuthiravali) 500g",
      category: "Pulses",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001023",
    },
    {
      id: "P024",
      name: "Horse Gram (Kollu) 500g",
      category: "Pulses",
      price: 55,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001024",
    },
    {
      id: "P025",
      name: "Sundal 1kg",
      category: "Pulses",
      price: 110,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001025",
    },
    {
      id: "P026",
      name: "Sundal 500g",
      category: "Pulses",
      price: 55,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001026",
    },
    {
      id: "P027",
      name: "Greengram (Paasi Payiru) 500g",
      category: "Pulses",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001027",
    },
    {
      id: "P028",
      name: "Soya Chunks (Big) 250g",
      category: "Pulses",
      price: 30,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001028",
    },
    {
      id: "P029",
      name: "Soya Chunks (Small) 250g",
      category: "Pulses",
      price: 30,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001029",
    },
    {
      id: "P030",
      name: "Solam (Sorghum) 500g",
      category: "Pulses",
      price: 30,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001030",
    },

    {
      id: "P031",
      name: "Coconut Oil 1L",
      category: "Oil Items",
      price: 450,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001031",
    },
    {
      id: "P032",
      name: "Coconut Oil 500ml",
      category: "Oil Items",
      price: 230,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001032",
    },
    {
      id: "P033",
      name: "Castor Oil (Vilakku Ennai) 250ml",
      category: "Oil Items",
      price: 75,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001033",
    },
    {
      id: "P034",
      name: "Castor Oil (Vilakku Ennai) 500ml",
      category: "Oil Items",
      price: 150,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001034",
    },
    {
      id: "P035",
      name: "Groundnut Oil 500ml",
      category: "Oil Items",
      price: 140,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001035",
    },
    {
      id: "P036",
      name: "Groundnut Oil 1L",
      category: "Oil Items",
      price: 275,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001036",
    },
    {
      id: "P037",
      name: "Gingelly Oil (Nallennai) 500ml",
      category: "Oil Items",
      price: 250,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001037",
    },

    {
      id: "P038",
      name: "Kavuni Barley Kanji Mix 250g",
      category: "Flour Items",
      price: 125,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001038",
    },
    {
      id: "P039",
      name: "Wheat Kurunai (Kottai Kambu) 500g",
      category: "Flour Items",
      price: 35,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001039",
    },
    {
      id: "P040",
      name: "Karuppu Kavuni Kurunai 500g",
      category: "Flour Items",
      price: 140,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001040",
    },
    {
      id: "P041",
      name: "Millet Dosa Mix 500g",
      category: "Flour Items",
      price: 100,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001041",
    },
    {
      id: "P042",
      name: "Multigrain Health Mix 250g",
      category: "Flour Items",
      price: 150,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001042",
    },
    {
      id: "P043",
      name: "Kambu Kurunai 500g",
      category: "Flour Items",
      price: 40,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001043",
    },
    {
      id: "P044",
      name: "Wheat Flour (Gothumai) 1kg",
      category: "Flour Items",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001044",
    },

    {
      id: "P045",
      name: "Millet Noodles (Varagu)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001045",
    },
    {
      id: "P046",
      name: "Semiya (Ragi / Tomato / Kambu) 225g",
      category: "Noodles & Semiya",
      price: 25,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001046",
    },
    {
      id: "P047",
      name: "Wheat Noodles (Gothumai) Big",
      category: "Noodles & Semiya",
      price: 160,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001047",
    },
    {
      id: "P048",
      name: "Millet Noodles (Kuthiravali)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001048",
    },
    {
      id: "P049",
      name: "Millet Noodles (Multigrain)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001049",
    },
    {
      id: "P050",
      name: "Millet Noodles (Thinai)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001050",
    },
    {
      id: "P051",
      name: "Millet Noodles (Sikappuvaragu)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001051",
    },
    {
      id: "P052",
      name: "Millet Noodles (Samai)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001052",
    },
    {
      id: "P053",
      name: "Millet Noodles (Kambu)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001053",
    },
    {
      id: "P054",
      name: "Millet Noodles (Ragi)",
      category: "Noodles & Semiya",
      price: 60,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001054",
    },

    {
      id: "P055",
      name: "Herbal Hair Oil 200g",
      category: "Skin Care",
      price: 175,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001055",
    },
    {
      id: "P056",
      name: "Nalangu Maavu Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001056",
    },
    {
      id: "P057",
      name: "Multhanimetti Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001057",
    },
    {
      id: "P058",
      name: "Vettiver Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001058",
    },
    {
      id: "P059",
      name: "Kuppaimeni Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001059",
    },
    {
      id: "P060",
      name: "Sandal Leaf Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001060",
    },
    {
      id: "P061",
      name: "Bathing Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001061",
    },
    {
      id: "P062",
      name: "Sandal Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001062",
    },
    {
      id: "P063",
      name: "Arisi Maavu Soap",
      category: "Skin Care",
      price: 70,
      purchasePrice: 0,
      gst: 0,
      stock: 50,
      lowStockLimit: 10,
      barcode: "8901001063",
    },
  ],
];

export let products = loadPersisted("products", seedProducts);

export const suppliers = [];

const seedCustomers = [];

export const customers = loadPersisted("customers", seedCustomers);

const purchaseSeeds = [];

function withPurchaseTotals(p) {
  return {
    ...p,
    totalQuantity: p.items.reduce((sum, i) => sum + Number(i.quantity || 0), 0),
  };
}

export const purchases = loadPersisted(
  "purchases",
  purchaseSeeds.map(withPurchaseTotals),
);

export const recentSales = [];

// Full bill records (with line items) for the History and Credit Bills
// screens. Dates are generated relative to "now" so the Today/Yesterday/
// This Week/This Month filters always have something to show regardless
// of when this demo data is viewed.
function daysAgo(n, hour = 14, minute = 30) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

const billSeeds = [];

export const bills = loadPersisted(
  "bills",
  billSeeds.map((seed) => {
    const subtotal = seed.items.reduce((sum, i) => sum + i.price * i.qty, 0);
    const gstAmount = seed.items.reduce(
      (sum, i) => sum + (i.price * i.qty * i.gst) / 100,
      0,
    );
    const total = Math.round((subtotal + gstAmount) * 100) / 100;
    return {
      id: seed.id,
      createdAt: daysAgo(seed.offset, seed.hour, seed.min),
      customerName: seed.customer?.name || null,
      customerMobile: seed.customer?.mobile || null,
      paymentMode: seed.mode,
      creditStatus:
        seed.mode === "Credit" ? seed.creditStatus || "pending" : "none",
      creditClosedMode: seed.closedMode || null,
      items: seed.items.map((i) => ({
        ...i,
        lineTotal:
          Math.round(
            (i.price * i.qty + (i.price * i.qty * i.gst) / 100) * 100,
          ) / 100,
      })),
      subtotal: Math.round(subtotal * 100) / 100,
      gstAmount: Math.round(gstAmount * 100) / 100,
      discountAmount: 0,
      total,
    };
  }),
);

export const salesTrend = [
  { day: "Mon", sales: 0 },
  { day: "Tue", sales: 0 },
  { day: "Wed", sales: 0 },
  { day: "Thu", sales: 0 },
  { day: "Fri", sales: 0 },
  { day: "Sat", sales: 0 },
  { day: "Sun", sales: 0 },
];

export const bestSellers = [];

export const sessions = loadPersisted("sessions", []);

export const dashboardStats = {
  todaySales: 0,
  monthlySales: 0,
  totalOrders: 0,
  totalProducts: products.length,
  totalRevenue: 0,
};

export const storeSettings = loadPersisted("settings", {
  storeName: "",
  gstNumber: "",
  gstDefaultRate: 0,
  address: "",
  billFooter: "",
  theme: "light",
  logoEmoji: "",
});
